package com.osh.chatting_bar_android.data_model;

public enum Categories {
    PHOTO,VOLUNTEERING,COSMETIC,OUTDOOR,HOME_DECO,DANCE,HISTORY,CAR,SPORT,DRAMA,MOVIE,STUDY,GAME,ART,MUSIC
    ,BOOK,HEALTH,CODING,FOOD,COOKING,KPOP,FASHION,WORK,TRAVEL,KIDS
}
